#!/bin/bash
# zip and push to s3
#
# Usage:
#  ./zipAndPush [profile]
# profile - optional AWS profile

# Configure here
s3_bucket="capitalone-hackathon1"
zip_name="getmeoutofhere.zip"

#####
if [ -z "$1" ]
  then
    profile="default"
  else
    profile=${1}
    echo "Using aws profile ${1}"
fi

# npm install
npm install

# zip js files for lambda
zip -r -q ${zip_name} *.js package.json node_modules

# push to AWS Bucket
aws s3 cp ${zip_name} s3://${s3_bucket} --profile ${profile}

echo "Uploaded to https://s3.amazonaws.com/${s3_bucket}/${zip_name}"
